[theme]
primaryColor = "#005BAC"  # Azul corporativo SABESP
backgroundColor = "#FFFFFF"  # Fundo branco
secondaryBackgroundColor = "#F0F2F6"  # Fundo levemente cinza para seções
textColor = "#262730"  # Texto escuro para contraste
font = "sans serif"  # Fonte limpa e profissional